### PR TITLE
Revert "Updated README Link import"

### PR DESCRIPTION
**Pull request by Alexendoo**
This reverts commit e195068ea62cd84cc2d5b4b9b02f7320cf893675.

activeClassName requires Link to be imported from match.js

### CODE REVIEW

**Comment by pmkroeker** [comment]
When I was testing I found that I had to import `Link` from root. Gave me errors trying to import from match.js.

**Comment by Alexendoo** [comment]
What errors did you run into? The link exported by the root and match do different things, only the one in match supports the activeClassName thing displayed in the README

**Comment by pmkroeker** [comment]
I was getting match does not export `Link`, which after looking at the code seems strange. Maybe it was an unrelated issue. Next time I'm using it I'll see what happens.

**Comment by marvinhagemeister** [comment]
Having two components with the same name do different things is confusing. Maybe we should revisit that decision and combine them or export them as different names all together?

**Comment by Alexendoo** [comment]
I think that would be a good idea. Perhaps we could bring in match.js's contents to index.js, with a re-export so it's not a breaking change.

**Comment by JLWalsh** [comment]
I also approve of this PR, I was really confused and had to dive in the code to figure out that there's a link exported by the router and a link exported by the match.

**Pull request merged**
